version: '3.8'

services:

  web:
    build:
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - type: bind
        source: ./docker/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf

  backend:
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html/src

  db:
    ports:
      - 3306:3306
    restart: unless-stopped
